Registration page Layout
287mdsahil/piradius pull request #9
Opened 2020-04-11 14:42 UTC by priyank23

This PR is in reference to issue #1 .
This adds a new page for registration of a student. It also links the page to the "Enroll Now" button in the home page.
Minor smelling errors in the about-us section is also corrected.

2020-04-12 12:28 UTC, 287mdsahil commented on about_us-partial.html
> +    <dt>Vision</dt>
Since this was not related to this issue, this should have been another commit.

2020-04-12 12:30 UTC, 287mdsahil commented on registration.html
> +<style>
The registration page will not have the navigation bar. Also, it should open in another tab.

2020-04-12 12:37 UTC, 287mdsahil commented on about_us-partial.html
> +    <dt>Vision</dt>
No need to change this one, 
Just mark it as resolved after you read it. :)

2020-04-12 13:08 UTC, 287mdsahil commented on registration.html
> +<style>
Also, rename this file as `registration-partial.html`

2020-04-12 13:09 UTC, 287mdsahil requested changes
rename the `registration.html` file as `registration-partial.html`

2020-04-12 13:11 UTC, 287mdsahil requested changes
The registration page should not have the navigation bar

2020-04-12 13:12 UTC, 287mdsahil requested changes
The registration page should open in a new tab

2020-04-13 07:13 UTC, priyank23 commented
@287mdsahil Check

2020-04-13 08:40 UTC, 287mdsahil commented
LGTM

2020-04-13 08:40 UTC, 287mdsahil approved these changes

2020-04-13 08:41 UTC, merged